development:
  host: localhost
  database: cmom_development

test:
  host: localhost
  database: cmom_test

# set these environment variables on your prod server
production:
  host: db1.solots.com 
  port: 27017
  database: cmom
  # username: <%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
